apiVersion: v1
kind: Service
metadata:
  name: zim-producer-service
spec:
  selector:
    app: zim-producer-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31036
  type: NodePort